name: Execute notebooks

on: [push]

jobs:
  static_analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - name: Run static analysis
        run: python scripts/validate.py

  run_notebook:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        notebook:
          # - hw_0.ipynb # uses input()s
          - hw_1.ipynb
          - hw_2.ipynb
          # - hw_3.ipynb # has incomplete code
          # - hw_4.ipynb # has incomplete code
          - hw_5.ipynb
          - hw_6.ipynb
          - lecture_0.ipynb
          # - lecture_1.ipynb # uses sample()
          - lecture_2.ipynb
          - lecture_3.ipynb
          - lecture_4.ipynb
          - lecture_5.ipynb
          # - lecture_5_exercise.ipynb # has incomplete code
          - lecture_6.ipynb
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: pip install -r .github/workflows/requirements.txt
      - name: Install TextBlob corpora
        if: matrix.notebook == 'lecture_5.ipynb'
        run: python -m textblob.download_corpora
      - name: Confirm notebook hasn't changed
        # live feed, so the output changes
        if: matrix.notebook != 'lecture_6.ipynb'
        run: ./scripts/check_change.sh ${{ matrix.notebook }}
